version: "3.7"
services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD : 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
